version: '3'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_container_1
    restart: always
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=fitbi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fitbi127
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fitbi
  pgamin:
    image: dpage/pgadmin4
    container_name: pgadmin_container_1
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=huynhtoan30@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=fitbi127
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-db
    networks:
      - fitbi

  metabase-app:
    image: metabase/metabase:latest
    container_name: metabase_1
    restart: always
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_NAME=fitbi
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=fitbi127
      - MB_DB_HOST=postgres-db
    depends_on:
      - postgres-db
    ports:
      - 3000:3000
    networks:
      - fitbi

networks:
  fitbi:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  